/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prediksipenumpangka;

import Controller.DatabaseManager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaff
 */
public final class ParameterHasilTraining extends javax.swing.JFrame {

    /**
     * Creates new form ParameterHasilTraining
     */
    public ParameterHasilTraining() {
        initComponents();
        
        setContentTabelParameterBP();
        setContentTabelParameterBPLM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        HasilTrainingBPLM = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_training_bplm = new javax.swing.JTable();
        HasilTrainingBP = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_training_bp = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        HasilTrainingBPLM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parameter Hail Training BPLM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        Tbl_training_bplm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Percobaan", "Epoch", "LM Parameter", "Beta Parameter"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tbl_training_bplm);

        javax.swing.GroupLayout HasilTrainingBPLMLayout = new javax.swing.GroupLayout(HasilTrainingBPLM);
        HasilTrainingBPLM.setLayout(HasilTrainingBPLMLayout);
        HasilTrainingBPLMLayout.setHorizontalGroup(
            HasilTrainingBPLMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HasilTrainingBPLMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        HasilTrainingBPLMLayout.setVerticalGroup(
            HasilTrainingBPLMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HasilTrainingBPLMLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        HasilTrainingBP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parameter Hasil Training BP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        Tbl_training_bp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Percobaan", "Epoch", "Learning Rate", "Min Error"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tbl_training_bp);

        javax.swing.GroupLayout HasilTrainingBPLayout = new javax.swing.GroupLayout(HasilTrainingBP);
        HasilTrainingBP.setLayout(HasilTrainingBPLayout);
        HasilTrainingBPLayout.setHorizontalGroup(
            HasilTrainingBPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HasilTrainingBPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HasilTrainingBPLayout.setVerticalGroup(
            HasilTrainingBPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HasilTrainingBPLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        Refresh.setText("Refresh Isi Tabel");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Refresh)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HasilTrainingBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HasilTrainingBPLM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HasilTrainingBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HasilTrainingBPLM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        setContentTabelParameterBP();
        setContentTabelParameterBPLM();
    }//GEN-LAST:event_RefreshActionPerformed

    public void setContentTabelParameterBP(){
        int i;
        DatabaseManager databaseManager;
        ArrayList<String[]> parameterBps; 
        String[] parameterBp;
        String sql_BP;
        
        databaseManager = new DatabaseManager();
        databaseManager.set_KoneksiDatabase();
        
        sql_BP = "select * from parameter_bp";
        parameterBps = databaseManager.getDataParameterBp(sql_BP);
        
        String[] row = new String[4];
        
        DefaultTableModel Training_BP = (DefaultTableModel) Tbl_training_bp.getModel();
        for(i=Tbl_training_bp.getRowCount()-1; i>=0; i--){
            Training_BP.removeRow(i);
        }
        
        for(i=0; i<parameterBps.size(); i++){
            parameterBp = parameterBps.get(i);

            row[0] = parameterBp[0];
            row[1] = parameterBp[1];
            row[2] = parameterBp[2];
            row[3] = parameterBp[3];

            Training_BP.addRow(row);
        }
    }
    
    public void setContentTabelParameterBPLM(){
        int i;
        DatabaseManager databaseManager;
        ArrayList<String[]> parameterBPLMs; 
        String[] parameterBPLM;
        String sql_BPLM;
        
        databaseManager = new DatabaseManager();
        databaseManager.set_KoneksiDatabase();
        
        sql_BPLM = "select * from parameter_bplm";
        parameterBPLMs = databaseManager.getDataParameterBPLM(sql_BPLM);
        
        String[] row = new String[4];
        DefaultTableModel Training_BPLM = (DefaultTableModel) Tbl_training_bplm.getModel();
        
        for(i=Tbl_training_bplm.getRowCount()-1; i>=0; i--){
            Training_BPLM.removeRow(i);
        }
        
        for(i=0; i<parameterBPLMs.size(); i++){
            parameterBPLM = parameterBPLMs.get(i);

            row[0] = parameterBPLM[0];
            row[1] = parameterBPLM[1];
            row[2] = parameterBPLM[2];
            row[3] = parameterBPLM[3];

            Training_BPLM.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParameterHasilTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParameterHasilTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParameterHasilTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParameterHasilTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParameterHasilTraining().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HasilTrainingBP;
    private javax.swing.JPanel HasilTrainingBPLM;
    private javax.swing.JButton Refresh;
    private javax.swing.JTable Tbl_training_bp;
    private javax.swing.JTable Tbl_training_bplm;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
