/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prediksipenumpangka;

import Controller.BP;
import Controller.BPLM;
import Controller.DatabaseManager;
import Controller.DokumenManager;
import java.io.File;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public final class Prediksi extends javax.swing.JFrame {

    /**
     * Creates new form Prediksi
     */
    private double[][] dataUji;
    private double[][] dataLatih;
    private double[] dataTahun;
    private boolean flagBp;
    private boolean flagBplm;
    public Prediksi() {
        initComponents();
        
        setContentTabelParameterBP();
        setContentTabelParameterBPLM();
        flagBp = false;
        flagBplm = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tbl_parameter_bp = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Mse_bp = new javax.swing.JLabel();
        Waktu_Eksekusi_bp = new javax.swing.JLabel();
        Iterasi_bp = new javax.swing.JLabel();
        prediksi_bp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Mse_bplm = new javax.swing.JLabel();
        Waktu_Eksekusi_bplm = new javax.swing.JLabel();
        Iterasi_bplm = new javax.swing.JLabel();
        prediksi_bplm = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tbl_parameter_bplm = new javax.swing.JTable();
        BBP = new javax.swing.JButton();
        Browse = new javax.swing.JButton();
        BBPLM = new javax.swing.JButton();
        BBMenuUtama = new javax.swing.JButton();
        cb_bulan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parameter BP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        Tbl_parameter_bp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Percobaan", "Epoch", "Learning Rate", "Min Error"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Tbl_parameter_bp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prediksi Penumpang KA (BP)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        Mse_bp.setText("Mean Square Error (MSE) : ");

        Waktu_Eksekusi_bp.setText("Waktu Eksekusi : ");

        Iterasi_bp.setText("Jumlah Iterasi : ");

        prediksi_bp.setText("Prediksi bulan ? : ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Mse_bp)
                        .addGap(276, 276, 276)
                        .addComponent(prediksi_bp))
                    .addComponent(Waktu_Eksekusi_bp)
                    .addComponent(Iterasi_bp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mse_bp)
                    .addComponent(prediksi_bp))
                .addGap(13, 13, 13)
                .addComponent(Waktu_Eksekusi_bp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Iterasi_bp)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prediksi Penumpang KA BPLM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        Mse_bplm.setText("Mean Square Error (MSE) : ");

        Waktu_Eksekusi_bplm.setText("Waktu Eksekusi : ");

        Iterasi_bplm.setText("Jumlah Iterasi : ");

        prediksi_bplm.setText("Prediksi bulan ? : ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Iterasi_bplm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Waktu_Eksekusi_bplm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Mse_bplm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prediksi_bplm)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mse_bplm)
                    .addComponent(prediksi_bplm))
                .addGap(13, 13, 13)
                .addComponent(Waktu_Eksekusi_bplm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Iterasi_bplm)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parameter BPLM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        Tbl_parameter_bplm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Percobaan", "Epoch", "LM Parameter", "Beta Parameter"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Tbl_parameter_bplm);

        BBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BBP, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BBP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Browse.setText("Load Excel");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        BBPLM.setText("Proses BPLM");
        BBPLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBPLMActionPerformed(evt);
            }
        });

        BBMenuUtama.setText("Balik ke Menu Utama");
        BBMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBMenuUtamaActionPerformed(evt);
            }
        });

        cb_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel1.setText("Bulan Prediksi :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Browse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_bulan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BBMenuUtama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BBPLM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(194, 194, 194))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Browse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BBPLM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BBMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        // TODO add your handling code here:
        int i,j, nBulan, nTahun;
        ArrayList<ArrayList> data;
        ArrayList<ArrayList> dataLatihExcel;

        DokumenManager dokManager = new DokumenManager();
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if(result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file : " + selectedFile.getAbsolutePath());
            String FILE_NAME = selectedFile.getAbsolutePath();
            data = dokManager.get_data(FILE_NAME);
            dataLatihExcel = dokManager.get_data("C:\\Users\\User\\Documents\\NetBeansProjects\\Program Tugas Akhir\\DataLatih1.xlsx");
            
            nBulan = data.get(0).size()-1;
            nTahun = data.size()-1;
            
            dataUji = new double[nTahun+1][nBulan];
            dataTahun = new double[nTahun];

            for(i=0; i<dataLatihExcel.get(0).size()-1; i++){
                dataUji[0][i] = Double.parseDouble(dataLatihExcel.get(dataLatihExcel.size()-1).get(i+1).toString());
            }
            
            for(i=0; i<nTahun; i++){
                //System.out.println("Data ke-" + i + ": ");
                for(j=0; j<nBulan; j++){
                    dataUji[i+1][j] = Double.parseDouble(data.get(i+1).get(j+1).toString());
                }
            }            
            
            for(i=0; i<nTahun; i++){
                dataTahun[i] = Double.parseDouble(data.get(i+1).get(0).toString());
            }
            
            flagBp = true;
            flagBplm =true;
            
            JOptionPane.showMessageDialog(null, "Pengambilan data pada file excel berhasil dilakukan.");
        }
    }//GEN-LAST:event_BrowseActionPerformed

    private void BBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBPActionPerformed
        // TODO add your handling code here:
        int nEpoch;
        double MSE;
        BP bp = new BP();
        ArrayList<double[]> dataPenumpangList;
        double[] dataPenumpang;
        
        int i, target;
        String dataTampil= "Jumlah penumpang pada tahun prediksi menggunakan Back-Propagation : \n";
        String Bulan="";

        DefaultTableModel parameter_bp = (DefaultTableModel) Tbl_parameter_bp.getModel();
        
        int baris = Tbl_parameter_bp.getSelectedRow();
        
        if(baris != -1 && flagBp == true){
            String percobaan = Tbl_parameter_bp.getValueAt(baris, 0).toString();
            String epoch = Tbl_parameter_bp.getValueAt(baris, 1).toString();
            String alpha = Tbl_parameter_bp.getValueAt(baris, 2).toString();
            String error = Tbl_parameter_bp.getValueAt(baris, 3).toString();

            long startTime = System.nanoTime();
            
            bp.inisialisasiDataUji(dataUji, 5, Integer.parseInt(percobaan), Double.parseDouble(epoch), Double.parseDouble(alpha), Double.parseDouble(error));
            bp.BackPropagationUji(3, 1);
            
            long elapsedTime = System.nanoTime() - startTime;
            double elapsedTimeInSeconds = TimeUnit.MILLISECONDS.convert(elapsedTime, TimeUnit.NANOSECONDS) / 1000.0;
            
            dataPenumpangList = bp.getDataOutputUji();
            
            switch (cb_bulan.getSelectedItem().toString()) {
                case "Januari":
                    target = 0;
                    break;
                case "Februari":
                    target = 1;
                    break;
                case "Maret":
                    target = 2;
                    break;
                case "April":
                    target = 3;
                    break;
                case "Mei":
                    target = 4;
                    break;
                case "Juni":
                    target = 5;
                    break;
                case "Juli":
                    target = 6;
                    break;
                case "Agustus":
                    target = 7;
                    break;
                case "September":
                    target = 8;
                    break;
                case "Oktober":
                    target = 9;
                    break;
                case "November":
                    target = 10;
                    break;
                default:
                    target = 11;
                    break;
            }
            
            prediksi_bp.setText("Prediksi Bulan "+cb_bulan.getSelectedItem().toString()+" : "+(int)dataPenumpangList.get(0)[target]);
            nEpoch = bp.getNEpoch();
            MSE = bp.getMSE();
            
            Mse_bp.setText("MSE : "+MSE);
            Iterasi_bp.setText("Iterasi : "+nEpoch);
            Waktu_Eksekusi_bp.setText("Waktu Eksekusi : "+elapsedTimeInSeconds+" s");
            
            JOptionPane.showMessageDialog(null, "Pelatihan menggunakan metode Back-propagation berhasil dilakukan.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Anda belum memilih parameter atau file excel yang akan digunakan.");
        }
        
        //TAHasilOutputBP.setText(dataTampil);
    }//GEN-LAST:event_BBPActionPerformed

    private void BBPLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBPLMActionPerformed
        // TODO add your handling code here:
        int nEpoch;
        double MSE;
        BPLM bplm = new BPLM();
        ArrayList<double[]> dataPenumpangList;
        double[] dataPenumpang;
        int i, target;
        
        DefaultTableModel parameter_bplm = (DefaultTableModel) Tbl_parameter_bplm.getModel();
        
        int baris = Tbl_parameter_bplm.getSelectedRow();
        
        if(baris != -1 && flagBp == true){
            String percobaan = Tbl_parameter_bplm.getValueAt(baris, 0).toString();
            String epoch = Tbl_parameter_bplm.getValueAt(baris, 1).toString();
            String lm = Tbl_parameter_bplm.getValueAt(baris, 2).toString();
            String beta = Tbl_parameter_bplm.getValueAt(baris, 3).toString();

            long startTime = System.nanoTime();
            
            bplm.inisialisasiDataUji(dataUji, 5, Integer.parseInt(percobaan), Double.parseDouble(epoch), Double.parseDouble(lm), Double.parseDouble(beta));
            bplm.BPLMUji(3, 1);
            
            long elapsedTime = System.nanoTime() - startTime;
            double elapsedTimeInSeconds = TimeUnit.MILLISECONDS.convert(elapsedTime, TimeUnit.NANOSECONDS) / 1000.0;
            
            dataPenumpangList = bplm.getDataOutputUji();
            
            switch (cb_bulan.getSelectedItem().toString()) {
                case "Januari":
                    target = 0;
                    break;
                case "Februari":
                    target = 1;
                    break;
                case "Maret":
                    target = 2;
                    break;
                case "April":
                    target = 3;
                    break;
                case "Mei":
                    target = 4;
                    break;
                case "Juni":
                    target = 5;
                    break;
                case "Juli":
                    target = 6;
                    break;
                case "Agustus":
                    target = 7;
                    break;
                case "September":
                    target = 8;
                    break;
                case "Oktober":
                    target = 9;
                    break;
                case "November":
                    target = 10;
                    break;
                default:
                    target = 11;
                    break;
            }
            
            prediksi_bplm.setText("Prediksi Bulan "+cb_bulan.getSelectedItem().toString()+" : "+(int)dataPenumpangList.get(0)[target]);
            
            nEpoch = bplm.getNEpoch();
            MSE = bplm.getMSE();
            
            Mse_bplm.setText("MSE : "+MSE);
            Iterasi_bplm.setText("Iterasi : "+nEpoch);
            Waktu_Eksekusi_bplm.setText("Waktu Eksekusi : "+elapsedTimeInSeconds+" s");

            JOptionPane.showMessageDialog(null, "Pelatihan menggunakan metode Back-propagation LEVENBERG-MARQUARDT berhasil dilakukan.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Anda belum memilih parameter atau file excel yang akan digunakan.");
        }
    }//GEN-LAST:event_BBPLMActionPerformed

    private void BBMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBMenuUtamaActionPerformed
        // TODO add your handling code here:
        MenuUtama menuUtama = new MenuUtama();
        menuUtama.setVisible(true);
        dispose();
    }//GEN-LAST:event_BBMenuUtamaActionPerformed

    public void setContentTabelParameterBP(){
        int i;
        DatabaseManager databaseManager;
        ArrayList<String[]> parameterBps; 
        String[] parameterBp;
        String sql_BP;
        
        databaseManager = new DatabaseManager();
        databaseManager.set_KoneksiDatabase();
        
        sql_BP = "select * from parameter_bp";
        parameterBps = databaseManager.getDataParameterBp(sql_BP);
        
        String[] row = new String[4];
        
        DefaultTableModel Training_BP = (DefaultTableModel) Tbl_parameter_bp.getModel();
        for(i=Tbl_parameter_bp.getRowCount()-1; i>=0; i--){
            Training_BP.removeRow(i);
        }
        
        for(i=0; i<parameterBps.size(); i++){
            parameterBp = parameterBps.get(i);

            row[0] = parameterBp[0];
            row[1] = parameterBp[1];
            row[2] = parameterBp[2];
            row[3] = parameterBp[3];

            Training_BP.addRow(row);
        }
    }
    
    public void setContentTabelParameterBPLM(){
        int i;
        DatabaseManager databaseManager;
        ArrayList<String[]> parameterBPLMs; 
        String[] parameterBPLM;
        String sql_BPLM;
        
        databaseManager = new DatabaseManager();
        databaseManager.set_KoneksiDatabase();
        
        sql_BPLM = "select * from parameter_bplm";
        parameterBPLMs = databaseManager.getDataParameterBPLM(sql_BPLM);
        
        String[] row = new String[4];
        DefaultTableModel Training_BPLM = (DefaultTableModel) Tbl_parameter_bplm.getModel();
        
        for(i=Tbl_parameter_bplm.getRowCount()-1; i>=0; i--){
            Training_BPLM.removeRow(i);
        }
        
        for(i=0; i<parameterBPLMs.size(); i++){
            parameterBPLM = parameterBPLMs.get(i);

            row[0] = parameterBPLM[0];
            row[1] = parameterBPLM[1];
            row[2] = parameterBPLM[2];
            row[3] = parameterBPLM[3];

            Training_BPLM.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prediksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBMenuUtama;
    private javax.swing.JButton BBP;
    private javax.swing.JButton BBPLM;
    private javax.swing.JButton Browse;
    private javax.swing.JLabel Iterasi_bp;
    private javax.swing.JLabel Iterasi_bplm;
    private javax.swing.JLabel Mse_bp;
    private javax.swing.JLabel Mse_bplm;
    private javax.swing.JTable Tbl_parameter_bp;
    private javax.swing.JTable Tbl_parameter_bplm;
    private javax.swing.JLabel Waktu_Eksekusi_bp;
    private javax.swing.JLabel Waktu_Eksekusi_bplm;
    private javax.swing.JComboBox<String> cb_bulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel prediksi_bp;
    private javax.swing.JLabel prediksi_bplm;
    // End of variables declaration//GEN-END:variables
}
